import java.io.FileNotFoundException;
import java.io.IOException;

import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import java.awt.Component;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*package javaapplication1;*/

/**
 *
 * @author user
 */
public class Event_add_trip extends javax.swing.JFrame {

    /**
     * Creates new form Event_add
     */
    public Event_add_trip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(843, 900));
        setSize(new java.awt.Dimension(800, 1000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Add trip");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Start date:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Event title:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Tickets:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Discount:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Sponsor:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Price:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("pcs.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("DKK");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Start time:");

        jTextField6.setPreferredSize(new java.awt.Dimension(6, 25));

        jTextField10.setPreferredSize(new java.awt.Dimension(6, 25));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try
               {
                  jButton3ActionPerformed(evt);
               }
               catch (NumberFormatException | IOException e)
               {
                  e.printStackTrace();
               }
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try
               {
                  jButton2ActionPerformed(evt);
               }
               catch (NumberFormatException | IOException e)
               {
                  e.printStackTrace();
               }
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("Duration:");

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.setPreferredSize(new java.awt.Dimension(12, 25));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("days");

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("%");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Locations:");
        
        textField = new JTextField();
        textField.setColumns(10);
        
        textField_1 = new JTextField();
        textField_1.setColumns(10);
        
        textField_2 = new JTextField();
        textField_2.setColumns(10);
        
        textField_3 = new JTextField();
        textField_3.setColumns(10);
        
        textField_4 = new JTextField();
        textField_4.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
           layout.createParallelGroup(Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                 .addGap(50)
                 .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 703, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                       .addGap(3)
                       .addGroup(layout.createParallelGroup(Alignment.LEADING)
                          .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 320, GroupLayout.PREFERRED_SIZE)
                          .addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, 715, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 715, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel9)
                       .addGap(56)
                       .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(ComponentPlacement.UNRELATED)
                       .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(Alignment.LEADING)
                          .addComponent(jLabel19)
                          .addComponent(jLabel15)
                          .addComponent(jLabel4))
                       .addGap(19)
                       .addGroup(layout.createParallelGroup(Alignment.LEADING)
                          .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                             .addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)
                             .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE))
                          .addGroup(layout.createSequentialGroup()
                             .addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                             .addPreferredGap(ComponentPlacement.RELATED)
                             .addComponent(jLabel13))))
                    .addGroup(layout.createSequentialGroup()
                       .addGap(400)
                       .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
                       .addGap(18)
                       .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
                       .addGap(18)
                       .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel8)
                       .addGap(32)
                       .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 296, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel5)
                       .addGap(18)
                       .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 296, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel6)
                       .addGap(41)
                       .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(ComponentPlacement.UNRELATED)
                       .addGroup(layout.createParallelGroup(Alignment.LEADING)
                          .addComponent(jLabel10)
                          .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(Alignment.LEADING)
                          .addComponent(jLabel7)
                          .addComponent(jLabel16))
                       .addGap(24)
                       .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                          .addComponent(textField)
                          .addComponent(jTextField3, GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                          .addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                          .addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                          .addComponent(textField_3, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                          .addComponent(textField_4, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE))))
                 .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
           layout.createParallelGroup(Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                 .addGap(25)
                 .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                 .addGap(20)
                 .addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                 .addGap(30)
                 .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel4)
                       .addGap(18)
                       .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                       .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                       .addGap(25)
                       .addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                 .addGap(25)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
                 .addGap(30)
                 .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                 .addGap(30)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                 .addGap(25)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                 .addGap(25)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                 .addGap(25)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                 .addGap(25)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                 .addGap(25)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                 .addGap(18)
                 .addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                 .addGap(18)
                 .addComponent(textField_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                 .addGap(18)
                 .addComponent(textField_3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                 .addGap(18)
                 .addComponent(textField_4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                 .addGap(10)
                 .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                 .addPreferredGap(ComponentPlacement.UNRELATED)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                 .addGap(35))
        );
        layout.linkSize(SwingConstants.VERTICAL, new Component[] {jButton3, jButton2});
        layout.linkSize(SwingConstants.VERTICAL, new Component[] {jLabel5, jLabel6, jLabel7, jLabel8});
        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jButton3, jButton2});
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, IOException {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
        new List_Events().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, IOException {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
       String startDate = jTextField6.getText();
       String startTime = jTextField10.getText();
       String duration = jTextField11.getText();
       String title = jTextField1.getText();
       String tickets = jTextField2.getText();
       String discount = jTextField3.getText();
       String price = jTextField4.getText();

       // startDate conversion
       String[] numbers = startDate.split("\\.");

       int[] results = new int[numbers.length];
       try
       {
          for (int i = 0; i < numbers.length; i++)
          {
             results[i] = Integer.parseInt(numbers[i]);
          }
       }
       catch (NumberFormatException e)
       {
          JOptionPane.showMessageDialog(null,
                "Please enter a valid input (use only numbers and dots) \nE.g: 15.12.2017");
       }
       Date date = new Date(results[0], results[1], results[2]);

       // startTime conversion
       String[] timeSplit = startTime.split("\\ ");

       int[] timeInt = new int[timeSplit.length];
       try
       {
          timeInt[0] = Integer.parseInt(timeSplit[0]);
          timeInt[1] = Integer.parseInt(timeSplit[1]);
       }
       catch (NumberFormatException e)
       {
          JOptionPane.showMessageDialog(null,
                "Please enter a valid input (use only numbers and spaces) \nE.g: 2 30");
       }
       Time startTimeObj = new Time(timeInt[0], timeInt[1]);

       // durationHour and durationMinute conversion
       int durationInt = 0;
       try
       {
          durationInt = Integer.parseInt(duration);
       }
       catch (NumberFormatException e)
       {
          JOptionPane.showMessageDialog(null,
                "Please enter a valid input (use only numbers) \nE.g: 2 30");
       }

       // tickets conversion
       int ticketsInt = 0;
       try
       {
          ticketsInt = Integer.parseInt(tickets);
       }
       catch (NumberFormatException e)
       {
          JOptionPane.showMessageDialog(null,
                "Please enter a valid input (use only numbers) \nE.g: 200");
       }

       // discount conversion
       int discountInt = 0;
       try
       {
          discountInt = Integer.parseInt(discount);
       }
       catch (NumberFormatException e)
       {
          JOptionPane.showMessageDialog(null,
                "Please enter a valid input (use only numbers) \nE.g: 30");
       }

       // price conversion
       int priceInt = 0;
       try
       {
          priceInt = Integer.parseInt(price);
       }
       catch (NumberFormatException e)
       {
          JOptionPane.showMessageDialog(null,
                "Please enter a valid input (use only numbers) \nE.g: 100");
       }
       
       //getting locations
       int counter = 0;
       String[] locations;
       if (!(textField.getText().isEmpty()))
       {
          counter++;
       }
       if (!(textField_1.getText().isEmpty()))
       {
          counter++;
       }
       if (!(textField_2.getText().isEmpty()))
       {
          counter++;
       }
       if (!(textField_3.getText().isEmpty()))
       {
          counter++;
       }
       if (!(textField_4.getText().isEmpty()))
       {
          counter++;
       }
       locations = new String[counter];
       counter = 0;
       if (!(textField.getText().isEmpty()))
       {
          locations[counter] = textField.getText();
          counter++;
       }
       if (!(textField_1.getText().isEmpty()))
       {
          locations[counter] = textField_2.getText();
          counter++;
       }
       if (!(textField_2.getText().isEmpty()))
       {
          locations[counter] = textField_3.getText();
          counter++;
       }
       if (!(textField_3.getText().isEmpty()))
       {
          locations[counter] = textField_3.getText();
          counter++;
       }
       if (!(textField_4.getText().isEmpty()))
       {
          locations[counter] = textField_4.getText();
          counter++;
       }  
       
       Trip trip = new Trip();
       trip.setDiscount(discountInt);
       trip.setDuration(durationInt);
       trip.setFinalized(false);
       trip.setPrice(priceInt);
       trip.setStartDate(date);
       trip.setStartTime(startTimeObj);
       trip.setTitle(title);
       trip.setTotalTickets(ticketsInt);
       trip.setLocations(locations);
       
       VIASystem.events.addEvent(trip);
       
       this.setVisible(false);
       new List_Events().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new Event_add_Define().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event_add_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event_add_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event_add_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event_add_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event_add_trip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private JTextField textField;
    private JTextField textField_1;
    private JTextField textField_2;
    private JTextField textField_3;
    private JTextField textField_4;
}
