import javax.swing.GroupLayout.Alignment;

import java.util.InputMismatchException;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import java.awt.Component;
import java.awt.TexturePaint;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

import javax.swing.JTextPane;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JTextArea;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*package javaapplication1;*/

/**
 * @author user
 */
public class Event_add_lecture extends javax.swing.JFrame
{

   /**
    * Creates new form Event_add
    */
   public Event_add_lecture() throws IOException
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated
   // Code">//GEN-BEGIN:initComponents
   private void initComponents() throws IOException
   {

      jLabel1 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      jTextField1 = new javax.swing.JTextField();
      jTextField2 = new javax.swing.JTextField();
      jTextField3 = new javax.swing.JTextField();
      jTextField4 = new javax.swing.JTextField();
      jTextField5 = new javax.swing.JTextField();
      jLabel10 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      jSeparator4 = new javax.swing.JSeparator();
      jPanel2 = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      jComboBox2 = new javax.swing.JComboBox<>();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      jLabel12 = new javax.swing.JLabel();
      jLabel15 = new javax.swing.JLabel();
      jSeparator1 = new javax.swing.JSeparator();
      jTextField6 = new javax.swing.JTextField();
      jTextField10 = new javax.swing.JTextField();
      jButton3 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jLabel19 = new javax.swing.JLabel();
      jTextField11 = new javax.swing.JTextField();
      jLabel13 = new javax.swing.JLabel();
      jTextField12 = new javax.swing.JTextField();
      jLabel14 = new javax.swing.JLabel();
      jButton4 = new javax.swing.JButton();
      jSeparator2 = new javax.swing.JSeparator();
      jSeparator3 = new javax.swing.JSeparator();
      jLabel16 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setMinimumSize(new java.awt.Dimension(800, 700));
      setPreferredSize(new java.awt.Dimension(800, 900));
      setSize(new java.awt.Dimension(800, 900));

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      jLabel1.setText("Add lecture");

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel4.setText("Start date:");

      jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel5.setText("Event title:");

      jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel6.setText("Tickets:");

      jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel7.setText("Discount:");

      jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel8.setText("Sponsor:");

      jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel9.setText("Price:");

      jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jTextField1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField1ActionPerformed(evt);
         }
      });

      jTextField2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      jTextField2.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField2ActionPerformed(evt);
         }
      });

      jTextField3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      jTextField3.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField3ActionPerformed(evt);
         }
      });

      jTextField4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      jTextField4.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField4ActionPerformed(evt);
         }
      });

      jTextField5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jTextField5.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField5ActionPerformed(evt);
         }
      });

      jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jLabel10.setText("pcs.");

      jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jLabel11.setText("DKK");

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel3.setText("Lecturer: ");

      jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      
      //getting lecturers
      
      Lecturer[] a = VIASystem.lecturers.getAllLecturersArray();
      jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(a));
      jComboBox2.setRenderer(new LecturerListCellRenderer());
      jComboBox2.setMinimumSize(new java.awt.Dimension(94, 25));
      jComboBox2.setPreferredSize(new java.awt.Dimension(94, 25));

      jTextArea1.setColumns(20);
      jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jTextArea1.setRows(5);
      jScrollPane1.setViewportView(jTextArea1);

      jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel12.setText("Subject:");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
            jPanel2);
      jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3).addGap(29)
                        .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE,
                              160, GroupLayout.PREFERRED_SIZE)
                        .addGap(71).addComponent(jLabel12)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE,
                              297, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE)));
      jPanel2Layout.setVerticalGroup(jPanel2Layout
            .createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup().addGap(2)
                  .addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel2Layout
                              .createParallelGroup(Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(jComboBox2,
                                    GroupLayout.PREFERRED_SIZE, 23,
                                    GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel12))
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE,
                              167, GroupLayout.PREFERRED_SIZE))
                  .addContainerGap(28, Short.MAX_VALUE)));
      jPanel2.setLayout(jPanel2Layout);

      jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel15.setText("Start time:");

      jTextField6.setPreferredSize(new java.awt.Dimension(6, 25));
      jTextField6.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField6ActionPerformed(evt);
         }
      });

      jTextField10.setPreferredSize(new java.awt.Dimension(6, 25));

      jButton3.setText("Add");
      jButton3.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
      
               try
               {
                  jButton3ActionPerformed(evt);
               }
               catch (NumberFormatException | IOException e)
               {
                  e.printStackTrace();
               }
            
         }
      });

      jButton2.setText("Cancel");
      jButton2.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            try
            {
               jButton2ActionPerformed(evt);
            }
            catch (NumberFormatException | IOException e)
            {
               e.printStackTrace();
            }
         }
      });

      jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel19.setText("Duration:");

      jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      jTextField11.setMinimumSize(new java.awt.Dimension(6, 25));
      jTextField11.setPreferredSize(new java.awt.Dimension(12, 25));

      jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
      jLabel13.setText("h");

      jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      jTextField12.setPreferredSize(new java.awt.Dimension(18, 25));
      jTextField12.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField12ActionPerformed(evt);
         }
      });

      jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
      jLabel14.setText("min");

      jButton4.setText("Back");
      jButton4.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButton4ActionPerformed(evt);
         }
      });

      jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jLabel16.setText("%");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane());
      layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addGap(50).addGroup(layout
                  .createParallelGroup(Alignment.TRAILING)
                  .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 93,
                              GroupLayout.PREFERRED_SIZE)
                        .addGap(18)
                        .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 93,
                              GroupLayout.PREFERRED_SIZE)
                        .addGap(18)
                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 93,
                              GroupLayout.PREFERRED_SIZE)
                        .addGap(75))
                  .addGroup(layout.createSequentialGroup().addGroup(layout
                        .createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel8).addGap(32).addComponent(
                                    jTextField5, GroupLayout.PREFERRED_SIZE,
                                    296, GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel9).addGap(56)
                              .addComponent(jTextField4,
                                    GroupLayout.PREFERRED_SIZE, 161,
                                    GroupLayout.PREFERRED_SIZE)
                              .addGap(18).addComponent(jLabel11))
                        .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel5).addGap(18).addComponent(
                                    jTextField1, GroupLayout.PREFERRED_SIZE,
                                    296, GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel19).addGap(27)
                              .addComponent(jTextField11,
                                    GroupLayout.PREFERRED_SIZE, 42,
                                    GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(ComponentPlacement.RELATED)
                              .addComponent(jLabel13).addGap(18)
                              .addComponent(jTextField12,
                                    GroupLayout.PREFERRED_SIZE, 42,
                                    GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(ComponentPlacement.RELATED)
                              .addComponent(jLabel14))
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                              .createParallelGroup(Alignment.LEADING)
                              .addComponent(jLabel15).addComponent(jLabel4))
                              .addGap(19)
                              .addGroup(layout
                                    .createParallelGroup(Alignment.TRAILING)
                                    .addComponent(jTextField10,
                                          GroupLayout.PREFERRED_SIZE, 193,
                                          GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6,
                                          GroupLayout.PREFERRED_SIZE, 193,
                                          GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE,
                              GroupLayout.DEFAULT_SIZE,
                              GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup().addGap(3)
                              .addGroup(layout
                                    .createParallelGroup(Alignment.LEADING)
                                    .addComponent(jLabel1,
                                          GroupLayout.PREFERRED_SIZE, 320,
                                          GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4,
                                          GroupLayout.PREFERRED_SIZE, 715,
                                          GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE,
                              GroupLayout.DEFAULT_SIZE,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 723,
                              Short.MAX_VALUE)
                        .addComponent(jSeparator2, GroupLayout.DEFAULT_SIZE,
                              723, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                              .createParallelGroup(Alignment.LEADING, false)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7).addGap(29)
                                    .addComponent(jTextField3))
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6).addGap(41)
                                    .addComponent(jTextField2,
                                          GroupLayout.PREFERRED_SIZE, 161,
                                          GroupLayout.PREFERRED_SIZE)))
                              .addPreferredGap(ComponentPlacement.UNRELATED)
                              .addGroup(layout
                                    .createParallelGroup(Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel16))))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE)))));
      layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addGap(25)
                  .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 30,
                        GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(ComponentPlacement.RELATED)
                  .addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                  .addGap(30)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel4).addComponent(jTextField6,
                              GroupLayout.PREFERRED_SIZE,
                              GroupLayout.DEFAULT_SIZE,
                              GroupLayout.PREFERRED_SIZE))
                  .addGap(18)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel15).addComponent(jTextField10,
                              GroupLayout.PREFERRED_SIZE,
                              GroupLayout.DEFAULT_SIZE,
                              GroupLayout.PREFERRED_SIZE))
                  .addGap(20)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jTextField11, GroupLayout.PREFERRED_SIZE,
                              GroupLayout.DEFAULT_SIZE,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jTextField12, GroupLayout.PREFERRED_SIZE,
                              GroupLayout.DEFAULT_SIZE,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                  .addGap(30)
                  .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10,
                        GroupLayout.PREFERRED_SIZE)
                  .addGap(26)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 20,
                              Short.MAX_VALUE)
                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE,
                              27, GroupLayout.PREFERRED_SIZE))
                  .addGap(20)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 27,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE,
                              27, GroupLayout.PREFERRED_SIZE))
                  .addGap(20)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 20,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE,
                              27, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 27,
                              GroupLayout.PREFERRED_SIZE))
                  .addGap(20)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 20,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE,
                              27, GroupLayout.PREFERRED_SIZE))
                  .addGap(20)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE,
                              27, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                  .addGap(40)
                  .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10,
                        GroupLayout.PREFERRED_SIZE)
                  .addGap(14)
                  .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                  .addGap(20)
                  .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10,
                        GroupLayout.PREFERRED_SIZE)
                  .addGap(11)
                  .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 40,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 40,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 40,
                              GroupLayout.PREFERRED_SIZE))
                  .addGap(23)));
      layout.linkSize(SwingConstants.VERTICAL,
            new Component[] { jLabel5, jLabel6, jLabel7, jLabel8 });
      layout.linkSize(SwingConstants.VERTICAL,
            new Component[] { jButton3, jButton2 });
      layout.linkSize(SwingConstants.HORIZONTAL,
            new Component[] { jButton3, jButton2 });
      getContentPane().setLayout(layout);

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jTextField1ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jTextField1ActionPerformed

   private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jTextField2ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jTextField2ActionPerformed

   private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jTextField3ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jTextField3ActionPerformed

   private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jTextField4ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jTextField4ActionPerformed

   private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jTextField5ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jTextField5ActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, IOException
   {// GEN-FIRST:event_jButton2ActionPerformed
      this.setVisible(false);
      new List_Events().setVisible(true);
   }// GEN-LAST:event_jButton2ActionPerformed

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, IOException
   {// GEN-FIRST:event_jButton3ActionPerformed

      String startDate = jTextField6.getText();
      String startTime = jTextField10.getText();
      String durationHour = jTextField11.getText();
      String durationMinute = jTextField12.getText();
      String title = jTextField1.getText();
      String tickets = jTextField2.getText();
      String discount = jTextField3.getText();
      String sponsor = jTextField5.getText();
      String price = jTextField4.getText();
      String subject = jTextArea1.getText();

      // startDate conversion
      String[] numbers = startDate.split("\\.");

      int[] results = new int[numbers.length];
      try
      {
         for (int i = 0; i < numbers.length; i++)
         {
            results[i] = Integer.parseInt(numbers[i]);
         }
      }
      catch (NumberFormatException e)
      {
         JOptionPane.showMessageDialog(null,
               "Please enter a valid input (use only numbers and dots) \nE.g: 15.12.2017");
      }
      Date date = new Date(results[0], results[1], results[2]);

      // startTime conversion
      String[] timeSplit = startTime.split("\\ ");

      int[] timeInt = new int[timeSplit.length];
      try
      {
         timeInt[0] = Integer.parseInt(timeSplit[0]);
         timeInt[1] = Integer.parseInt(timeSplit[1]);
      }
      catch (NumberFormatException e)
      {
         JOptionPane.showMessageDialog(null,
               "Please enter a valid input (use only numbers and spaces) \nE.g: 2 30");
      }
      Time startTimeObj = new Time(timeInt[0], timeInt[1]);

      // durationHour and durationMinute conversion
      int durationHourInt = 0;
      int durationMinuteInt = 0;
      try
      {
         durationHourInt = Integer.parseInt(durationHour);
         durationMinuteInt = Integer.parseInt(durationMinute);
      }
      catch (NumberFormatException e)
      {
         JOptionPane.showMessageDialog(null,
               "Please enter a valid input (use only numbers) \nE.g: 2 30");
      }
      Time duration = new Time(durationHourInt, durationMinuteInt);

      // tickets conversion
      int ticketsInt = 0;
      try
      {
         ticketsInt = Integer.parseInt(tickets);
      }
      catch (NumberFormatException e)
      {
         JOptionPane.showMessageDialog(null,
               "Please enter a valid input (use only numbers) \nE.g: 200");
      }

      // discount conversion
      int discountInt = 0;
      try
      {
         discountInt = Integer.parseInt(discount);
      }
      catch (NumberFormatException e)
      {
         JOptionPane.showMessageDialog(null,
               "Please enter a valid input (use only numbers) \nE.g: 30");
      }

      // price conversion
      int priceInt = 0;
      try
      {
         priceInt = Integer.parseInt(price);
      }
      catch (NumberFormatException e)
      {
         JOptionPane.showMessageDialog(null,
               "Please enter a valid input (use only numbers) \nE.g: 100");
      }
      //getting lecturer
      Lecturer lecturerSelected = (Lecturer)jComboBox2.getSelectedItem();
      
      //creating new lecture
      Lecture lecture = new Lecture();
      lecture.setDiscount(discountInt);
      lecture.setDuration(duration);
      lecture.setFinalized(false);
      lecture.setPrice(priceInt);
      lecture.setSponsorName(sponsor);
      lecture.setStartTime(startTimeObj);
      lecture.setSubject(subject);
      lecture.setTitle(title);
      lecture.setTotalTickets(ticketsInt);
      lecture.setStartDate(date);
      lecture.setLecturer(lecturerSelected);
      
      VIASystem.events.addEvent(lecture);
      
      this.setVisible(false);
      new List_Events().setVisible(true);

   }// GEN-LAST:event_jButton3ActionPerformed

   private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jTextField12ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jTextField12ActionPerformed

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jButton4ActionPerformed
      this.setVisible(false);
      new Event_add_Define().setVisible(true);
   }// GEN-LAST:event_jButton4ActionPerformed

   private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jTextField6ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jTextField6ActionPerformed

   /**
    * @param args
    *           the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
      // (optional) ">
      /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the
       * default look and feel. For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
       * html
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
               .getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(Event_add_lecture.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(Event_add_lecture.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(Event_add_lecture.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(Event_add_lecture.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      // </editor-fold>
      // </editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            try
            {
               new Event_add_lecture().setVisible(true);
            }
            catch (IOException e)
            {
               e.printStackTrace();
            }
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JComboBox<Lecturer> jComboBox2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JSeparator jSeparator4;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField10;
   private javax.swing.JTextField jTextField11;
   private javax.swing.JTextField jTextField12;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JTextField jTextField3;
   private javax.swing.JTextField jTextField4;
   private javax.swing.JTextField jTextField5;
   private javax.swing.JTextField jTextField6;
}
