import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JComboBox;
import java.awt.Font;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*package javaapplication1;*/

/**
 * @author user
 */
public class List_Members extends javax.swing.JFrame
{

   /**
    * Creates new form EventsB
    * 
    * @throws IOException
    */
   public List_Members() throws IOException
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    * 
    * @throws IOException
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated
   // Code">//GEN-BEGIN:initComponents
   private void initComponents() throws IOException
   {

      jLabel1 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jTextField1 = new javax.swing.JTextField();
      jButton4 = new javax.swing.JButton();
      comboBox = new javax.swing.JComboBox<>();
      jScrollPane2 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList<>();
      jSeparator1 = new javax.swing.JSeparator();
      jLabel3 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Events");
      setMinimumSize(new java.awt.Dimension(300, 300));
      setModalExclusionType(
            java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
      setPreferredSize(new java.awt.Dimension(800, 900));
      setSize(new java.awt.Dimension(800, 900));

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      jLabel1.setText("Member List");

      jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jButton1.setText("Add");
      jButton1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jButton2.setText("Edit");
      jButton2.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            try
            {
               jButton2ActionPerformed(evt);
            }
            catch (FileNotFoundException e)
            {
               e.printStackTrace();
            }
         }
      });

      jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jButton3.setText("Delete");
      jButton3.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButton3ActionPerformed(evt);
         }
      });

      jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jTextField1.setToolTipText("");
      jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
      jTextField1.setName(""); // NOI18N
      jTextField1.setPreferredSize(new java.awt.Dimension(6, 25));
      jTextField1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField1ActionPerformed(evt);
         }
      });

      jButton4.setText("Back To Main Menu");
      jButton4.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButton4ActionPerformed(evt);
         }
      });

      // getting members

      Member[] membersArr = new Member[VIASystem.members.getAllMembers()
            .size()];
      for (int i = 0; i < VIASystem.members.getAllMembers().size(); i++)
      {
         membersArr[i] = VIASystem.members.getAllMembers().get(i);
      }

      jList1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
      jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      jList1.setListData(membersArr);
      jList1.setCellRenderer(new MemberListCellRenderer());
      jList1.setFixedCellHeight(50);
      jList1.addMouseListener(new MouseAdapter() {
         public void mouseClicked(MouseEvent evt) {
             JList list = (JList)evt.getSource();
             if (evt.getClickCount() == 2) {
                
                String message = new String();
                message = jList1.getSelectedValue().userToString();

                JOptionPane.showMessageDialog(null, message);
                
                 // Double-click detected
                 int index = list.locationToIndex(evt.getPoint());
             } else if (evt.getClickCount() == 3) {

                 // Triple-click detected
                 int index = list.locationToIndex(evt.getPoint());
             }
         }
     });
      jScrollPane2.setViewportView(jList1);

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel3.setText("Search:");

      comboBox.setModel(new DefaultComboBoxModel(new String[] { "Member name",
            "Payment year", "Date of registration", "Attended events" }));
      comboBox.setPreferredSize(new Dimension(87, 25));
      comboBox.setFont(new Font("Tahoma", Font.PLAIN, 14));

      JLabel lblBy = new JLabel("by:");

      JButton clearFilter = new JButton("");
      clearFilter.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            clearFilterActionPerformed(evt);
         }
      });
      clearFilter.setIcon(new ImageIcon(List_Members.class.getResource(
            "/com/sun/javafx/scene/control/skin/caspian/dialog-error.png")));
      clearFilter.setToolTipText("Clears the search filters");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane());
      layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup().addGap(50).addGroup(layout
                  .createParallelGroup(Alignment.TRAILING)
                  .addGroup(layout.createParallelGroup(Alignment.LEADING)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 320,
                              GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, Alignment.TRAILING,
                              GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE,
                              GroupLayout.DEFAULT_SIZE,
                              GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                              .addComponent(jButton1,
                                    GroupLayout.PREFERRED_SIZE, 99,
                                    GroupLayout.PREFERRED_SIZE)
                              .addGap(30)
                              .addComponent(jButton2,
                                    GroupLayout.PREFERRED_SIZE, 100,
                                    GroupLayout.PREFERRED_SIZE)
                              .addGap(30)
                              .addComponent(jButton3,
                                    GroupLayout.PREFERRED_SIZE, 100,
                                    GroupLayout.PREFERRED_SIZE)
                              .addGap(50)
                              .addGroup(layout
                                    .createParallelGroup(Alignment.TRAILING)
                                    .addComponent(jLabel3).addComponent(lblBy))
                              .addPreferredGap(ComponentPlacement.UNRELATED)
                              .addGroup(layout
                                    .createParallelGroup(Alignment.LEADING)
                                    .addComponent(comboBox,
                                          GroupLayout.PREFERRED_SIZE, 178,
                                          GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                          .addComponent(jTextField1,
                                                GroupLayout.PREFERRED_SIZE, 178,
                                                GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(
                                                ComponentPlacement.RELATED)
                                          .addComponent(clearFilter,
                                                GroupLayout.PREFERRED_SIZE, 22,
                                                GroupLayout.PREFERRED_SIZE)))))
                  .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 143,
                        GroupLayout.PREFERRED_SIZE))
                  .addGap(59)));
      layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addGap(50)
                  .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 25,
                        GroupLayout.PREFERRED_SIZE)
                  .addGap(20)
                  .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10,
                        GroupLayout.PREFERRED_SIZE)
                  .addGap(30)
                  .addGroup(layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                              .addComponent(jButton1,
                                    GroupLayout.PREFERRED_SIZE, 55,
                                    GroupLayout.PREFERRED_SIZE)
                              .addComponent(jButton2,
                                    GroupLayout.PREFERRED_SIZE, 55,
                                    GroupLayout.PREFERRED_SIZE)
                              .addComponent(jButton3,
                                    GroupLayout.PREFERRED_SIZE, 55,
                                    GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup().addGap(1)
                              .addGroup(layout
                                    .createParallelGroup(Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField1,
                                          GroupLayout.PREFERRED_SIZE,
                                          GroupLayout.DEFAULT_SIZE,
                                          GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearFilter,
                                          GroupLayout.PREFERRED_SIZE, 24,
                                          GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(ComponentPlacement.UNRELATED)
                              .addGroup(layout
                                    .createParallelGroup(Alignment.BASELINE)
                                    .addComponent(comboBox,
                                          GroupLayout.PREFERRED_SIZE, 25,
                                          GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBy))))
                  .addGap(32)
                  .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 482,
                        GroupLayout.PREFERRED_SIZE)
                  .addGap(29).addComponent(jButton4, GroupLayout.PREFERRED_SIZE,
                        32, GroupLayout.PREFERRED_SIZE)
                  .addGap(135)));
      getContentPane().setLayout(layout);

      jTextField1.getAccessibleContext().setAccessibleName("PPPP");

      getAccessibleContext().setAccessibleName("");

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void clearFilterActionPerformed(java.awt.event.ActionEvent evt)
   {
      jTextField1.setText("");

      Member[] eventsArr = new Member[VIASystem.members.getAllMembers().size()];
      for (int i = 0; i < VIASystem.members.getAllMembers().size(); i++)
      {
         eventsArr[i] = VIASystem.members.getAllMembers().get(i);
      }

      jList1.setListData(eventsArr);
   }

   private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jTextField1ActionPerformed
      // TODO add your handling code here:

      Member[] eventsArr = new Member[VIASystem.members.getAllMembers().size()];

      if (comboBox.getSelectedItem() == "Member name")
      {

         eventsArr = VIASystem.members.getMember(jTextField1.getText());

         jList1.setListData(eventsArr);
      }
      else if (comboBox.getSelectedItem() == "Payment year")
      {
         try
         {
            eventsArr = VIASystem.members
                  .getMember(Integer.parseInt(jTextField1.getText()));
            jList1.setListData(eventsArr);
         }
         catch (NumberFormatException e)
         {
            JOptionPane.showMessageDialog(null,
                  "Please enter a valid input (use only numbers) \nE.g: 2018");
         }
      }
      else if (comboBox.getSelectedItem() == "Lecturer name")
      {
         String[] numbers = jTextField1.getText().split("\\.");
         int[] results = new int[numbers.length];

         for (int i = 0; i < numbers.length; i++)
         {
            results[i] = Integer.parseInt(numbers[i]);
         }

         Date date = new Date(results[0], results[1], results[2]);
         eventsArr = VIASystem.members.getMember(date);
         jList1.setListData(eventsArr);
      }
      else if (comboBox.getSelectedItem() == "Attended events")
      {
         int counter = 0;
         for (int i = 0; i < VIASystem.members.getAllMembers().size(); i++)
         {
            for (int j = 0; j < VIASystem.members.getAllMembers().get(i)
                  .getAttendedEvents().size(); j++)
            {
               if(VIASystem.events.getEventById(Integer.parseInt(VIASystem.members.getAllMembers().get(i)
                  .getAttendedEvents().get(j))).getTitle().equals(jTextField1.getText()))
                     {
                        eventsArr[counter] = VIASystem.members.getAllMembers().get(i);
                        counter++;
                     }
            }
         }

         jList1.setListData(eventsArr);
      }

   }// GEN-LAST:event_jTextField1ActionPerformed

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jButton4ActionPerformed
      this.setVisible(false);
      new NewJFrame().setVisible(true);

   }// GEN-LAST:event_jButton4ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jButton1ActionPerformed

      this.setVisible(false);
      new Member_add().setVisible(true);

   }// GEN-LAST:event_jButton1ActionPerformed

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)
   {
      VIASystem.members.removeMember(jList1.getSelectedValue());

      // reseting jList1

      Member[] eventsArr = new Member[VIASystem.members.getAllMembers().size()];
      for (int i = 0; i < VIASystem.members.getAllMembers().size(); i++)
      {
         eventsArr[i] = VIASystem.members.getAllMembers().get(i);
      }

      jList1.setListData(eventsArr);
   }

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
         throws FileNotFoundException
   {// GEN-FIRST:event_jButton2ActionPerformed

      Member member = new Member(1);
      member = (Member) jList1.getSelectedValue();
      String name = "";
      String email = "";
      String phone = "";
      String address = "";
      String regDate = "";
      String payYear = "";
      String newsSub = "";
      String attendedEv = "";

      name = JOptionPane.showInputDialog("Enter a new name: "
            + "\n(leave empty if you do not wish to modify it)");

      email = JOptionPane.showInputDialog("Enter a new email address: "
            + "\n(leave empty if you do not wish to modify it)");

      phone = JOptionPane.showInputDialog("Enter a new phone number: "
            + "\n(leave empty if you do not wish to modify it)");

      address = JOptionPane.showInputDialog("Enter a new street address: "
            + "\n(leave empty if you do not wish to modify it)");

      regDate = JOptionPane.showInputDialog("Enter a new date of registration: "
            + "\n(leave empty if you do not wish to modify it)");

      payYear = JOptionPane.showInputDialog("Enter a new payment year: "
            + "\n(leave empty if you do not wish to modify it)");

      newsSub = JOptionPane.showInputDialog(
            "Is the member subscribed to your newsletter?(answer with yes or no) "
                  + "\n(leave empty if you do not wish to modify it)");

      attendedEv = JOptionPane
            .showInputDialog("Enter the names of the member's attended events: "
                  + "\n(leave empty if you do not wish to modify it)");

      if (name.length() != 0)
      {
         member.setName(name);
      }
      if (email.length() != 0)
      {
         member.setEmail(email);
      }
      if (phone.length() != 0)
      {
         member.setPhone(phone);
      }
      if (address.length() != 0)
      {
         member.setAddress(address);
      }
      if (regDate.length() != 0)
      {
         String[] numbers = regDate.split("\\.");

         int[] results = new int[numbers.length];
         try
         {
            for (int i = 0; i < numbers.length; i++)
            {
               results[i] = Integer.parseInt(numbers[i]);
            }
         }
         catch (NumberFormatException e)
         {
            JOptionPane.showMessageDialog(null,
                  "Please enter a valid input (use only numbers and dots) \nE.g: 15.12.2017");
         }
         Date date = new Date(results[0], results[1], results[2]);

         member.setDateOfRegistration(date);
      }
      if (payYear.length() != 0)
      {
         try
         {
            int payYearInt = Integer.parseInt(payYear);
            member.setPaymentYear(payYearInt);
         }
         catch (NumberFormatException e)
         {
            JOptionPane.showMessageDialog(null,
                  "Please enter a valid input (use only numbers) \nE.g: 2018");
         }
      }
      if (newsSub.length() != 0)
      {
         if (newsSub.equals("yes") || newsSub.equals("Yes"))
         {
            member.setNewsletterSubscription(true);
         }
         else if (newsSub.equals("no") || newsSub.equals("No"))
         {
            member.setNewsletterSubscription(false);
         }
         else
         {
            JOptionPane.showMessageDialog(null,
                  "Answer with yes or no for newsletter subscription");
         }
      }
      if (attendedEv.length() != 0)
      {
         ArrayList<String> evs = new ArrayList<String>();
         String[] ev = attendedEv.split(" ");
         for (int i = 0; i < ev.length; i++)
         {
            evs.add(ev[i]);
         }
         member.setAttendedEvents(evs);
      }

      member.writeToFile();
   }// GEN-LAST:event_jButton2ActionPerformed

   /**
    * @param args
    *           the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
      // (optional) ">
      /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the
       * default look and feel. For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
       * html
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
               .getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(List_Members.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(List_Members.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(List_Members.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(List_Members.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            try
            {
               new List_Members().setVisible(true);
            }
            catch (IOException e)
            {
               e.printStackTrace();
            }
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JComboBox<String> comboBox;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JList<Member> jList1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JTextField jTextField1;
}
