import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*package javaapplication1;*/

/**
 *
 * @author user
 */
public class List_Teachers extends javax.swing.JFrame {

    /**
     * Creates new form EventsB
    * @throws IOException 
     */
    public List_Teachers() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    * @throws IOException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws IOException {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Events");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(800, 900));
        setSize(new java.awt.Dimension(800, 900));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Lecturer List");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try
               {
                  jButton2ActionPerformed(evt);
               }
               catch (FileNotFoundException e)
               {
                  e.printStackTrace();
               }
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton3ActionPerformed(evt);
           }
       });
        
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setToolTipText("");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setName(""); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(6, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setText("Back To Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        //getting lecturers
        
        Lecturer[] lecturersArr = new Lecturer[VIASystem.lecturers.getAllLecturers().size()];
        for(int i = 0; i < VIASystem.lecturers.getAllLecturers().size(); i++)
        {
           lecturersArr[i] = VIASystem.lecturers.getAllLecturers().get(i);
        }
        
        
        jList1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setListData(lecturersArr);
        jList1.setCellRenderer(new LecturerListCellRenderer());
        jList1.setFixedCellHeight(20);
        jList1.addMouseListener(new MouseAdapter() {
           public void mouseClicked(MouseEvent evt) {
               JList list = (JList)evt.getSource();
               if (evt.getClickCount() == 2) {
                  
                  String message = new String();
                  message = jList1.getSelectedValue().userToString();

                  JOptionPane.showMessageDialog(null, message);
                  
                   // Double-click detected
                   int index = list.locationToIndex(evt.getPoint());
               } else if (evt.getClickCount() == 3) {

                   // Triple-click detected
                   int index = list.locationToIndex(evt.getPoint());
               }
           }
       });
        jScrollPane2.setViewportView(jList1);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new DefaultComboBoxModel(new String[] {"Lecturer name", "Email", "Phone", "Sponsors", "Non-sponsors", "Subject"}));
        jComboBox1.setPreferredSize(new java.awt.Dimension(87, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Search:");
        
        JLabel lblBy = new JLabel("by:");
        
        JButton button = new JButton("");
        button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
              buttonActionPerformed(evt);
          }
      });
        button.setIcon(new ImageIcon(List_Teachers.class.getResource("/com/sun/javafx/scene/control/skin/caspian/dialog-error.png")));
        button.setToolTipText("Clears the search filters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
           layout.createParallelGroup(Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                 .addContainerGap(50, Short.MAX_VALUE)
                 .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(Alignment.LEADING)
                       .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 320, GroupLayout.PREFERRED_SIZE)
                       .addComponent(jScrollPane2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                       .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                       .addGroup(layout.createSequentialGroup()
                          .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
                          .addGap(30)
                          .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                          .addGap(30)
                          .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                          .addGap(51)
                          .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                             .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE))
                             .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBy)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)))
                          .addPreferredGap(ComponentPlacement.RELATED)
                          .addComponent(button, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE))
                 .addGap(59))
        );
        layout.setVerticalGroup(
           layout.createParallelGroup(Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                 .addGap(50)
                 .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                 .addGap(20)
                 .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                 .addGap(30)
                 .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                       .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                       .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                       .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                       .addGap(1)
                       .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                          .addComponent(jLabel3)
                          .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                          .addComponent(button, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(ComponentPlacement.UNRELATED)
                       .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                          .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                          .addComponent(lblBy))))
                 .addGap(32)
                 .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 482, GroupLayout.PREFERRED_SIZE)
                 .addGap(29)
                 .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                 .addGap(135))
        );
        getContentPane().setLayout(layout);

        jTextField1.getAccessibleContext().setAccessibleName("PPPP");

        getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt)
    {
       jTextField1.setText("");

       Lecturer[] eventsArr = new Lecturer[VIASystem.lecturers.getAllLecturers().size()];
       for (int i = 0; i < VIASystem.lecturers.getAllLecturers().size(); i++)
       {
          eventsArr[i] = VIASystem.lecturers.getAllLecturers().get(i);
       }

       jList1.setListData(eventsArr);
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       
       Lecturer[] eventsArr = new Lecturer[VIASystem.lecturers.getAllLecturers().size()];
       
       if(jComboBox1.getSelectedItem() == "Lecturer name")
       {
          
             eventsArr[0] = VIASystem.lecturers.getLecturer(jTextField1.getText());
           
           jList1.setListData(eventsArr);
       }
       else if(jComboBox1.getSelectedItem() == "Email")
       {
            eventsArr = VIASystem.lecturers.getLecturerByEmail(jTextField1.getText());
            jList1.setListData(eventsArr);
       }
       else if(jComboBox1.getSelectedItem() == "Phone")
       {
          eventsArr = VIASystem.lecturers.getLecturerByPhone(jTextField1.getText());
          jList1.setListData(eventsArr);
       }
       else if(jComboBox1.getSelectedItem() == "Sponsors")
       {
          
          eventsArr = VIASystem.lecturers.getLecturer(true);
          jList1.setListData(eventsArr);
       }
       else if(jComboBox1.getSelectedItem() == "Non-sponsors")
       {
          eventsArr = VIASystem.lecturers.getLecturer(false);
          jList1.setListData(eventsArr);
       }
       else if(jComboBox1.getSelectedItem() == "Subject")
       {
          eventsArr = VIASystem.lecturers.getLecturerBySubject(jTextField1.getText());
          jList1.setListData(eventsArr);
       }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         this.setVisible(false);
        new NewJFrame().setVisible(true);
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
       VIASystem.lecturers.removeLecturer(jList1.getSelectedValue());

       // reseting jList1

       Lecturer[] eventsArr = new Lecturer[VIASystem.lecturers.getAllLecturers().size()];
       for (int i = 0; i < VIASystem.lecturers.getAllLecturers().size(); i++)
       {
          eventsArr[i] = VIASystem.lecturers.getAllLecturers().get(i);
       }

       jList1.setListData(eventsArr);
       
  }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                              
         this.setVisible(false);
        new Teacher_add().setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {//GEN-FIRST:event_jButton2ActionPerformed
        
       Lecturer lecturer = new Lecturer(1);
       lecturer = (Lecturer) jList1.getSelectedValue();
       String name = "";
       String email= "";
       String phone = "";
       String sponsor = "";
       String subject = "";

       name = JOptionPane.showInputDialog("Enter a new name: "
             + "\n(leave empty if you do not wish to modify it)");

       email = JOptionPane.showInputDialog("Enter a new email address: "
             + "\n(leave empty if you do not wish to modify it)");

       phone = JOptionPane.showInputDialog("Enter a new phone number: "
             + "\n(leave empty if you do not wish to modify it)");

       sponsor = JOptionPane.showInputDialog(
             "Is the lecturer a sponsor?(answer with yes or no) "
                   + "\n(leave empty if you do not wish to modify it)");

       subject = JOptionPane.showInputDialog("Enter the name of the lecturer's subject: "
             + "\n(leave empty if you do not wish to modify it)");

       if(name.length() != 0)
       {
          lecturer.setName(name);
       }
       if(email.length() != 0)
       {
          lecturer.setEmail(email);
       }
       if(phone.length() != 0)
       {
          lecturer.setPhone(phone);
       }
       if(sponsor.length() != 0)
       {
          if(sponsor.equals("yes") || sponsor.equals("Yes"))
          {
             lecturer.setSponsor(true);
          }
          else if(sponsor.equals("no") || sponsor.equals("No"))
          {
             lecturer.setSponsor(false);
          }
          else
          {
             JOptionPane.showMessageDialog(null, "Answer with yes or no for sponsorship status");
          }
       }
       if(subject.length() != 0)
       {
             lecturer.setSubject(subject);
       }
        
       lecturer.writeToFile();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
               {
                  new List_Teachers().setVisible(true);
               }
               catch (IOException e)
               {
                  e.printStackTrace();
               }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<Lecturer> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
}
