import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*package javaapplication1;*/

/**
 * @author user
 */
public class Member_add extends javax.swing.JFrame
{

   /**
    * Creates new form Event_add
    */
   public Member_add()
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated
   // Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jLabel1 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jSeparator4 = new javax.swing.JSeparator();
      jLabel15 = new javax.swing.JLabel();
      jTextField10 = new javax.swing.JTextField();
      jButton3 = new javax.swing.JButton();
      jLabel19 = new javax.swing.JLabel();
      jButton4 = new javax.swing.JButton();
      jSeparator3 = new javax.swing.JSeparator();
      jLabel16 = new javax.swing.JLabel();
      jTextField12 = new javax.swing.JTextField();
      jLabel20 = new javax.swing.JLabel();
      jTextField11 = new javax.swing.JTextField();
      jTextField13 = new javax.swing.JTextField();
      jLabel21 = new javax.swing.JLabel();
      jTextField14 = new javax.swing.JTextField();
      jLabel22 = new javax.swing.JLabel();
      jTextField15 = new javax.swing.JTextField();
      jLabel23 = new javax.swing.JLabel();
      jCheckBox2 = new javax.swing.JCheckBox();
      jScrollPane2 = new javax.swing.JScrollPane();
      jScrollPane1 = new javax.swing.JScrollPane();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setMinimumSize(new java.awt.Dimension(800, 700));
      setSize(new java.awt.Dimension(800, 1000));

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      jLabel1.setText("Add Member");

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel4.setText("Name:");

      jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel15.setText("Email");

      jTextField10.setPreferredSize(new java.awt.Dimension(6, 25));

      jButton3.setText("Add");
      jButton3.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            try
            {
               jButton3ActionPerformed(evt);
            }
            catch (NumberFormatException | IOException e)
            {
               e.printStackTrace();
            }
         }
      });

      jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel19.setText("Phone:");

      jButton4.setText("Cancel");
      jButton4.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            try
            {
               jButton4ActionPerformed(evt);
            }
            catch (IOException e)
            {
               e.printStackTrace();
            }
         }
      });

      jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel16.setText("Attended Events:");

      jTextField12.setPreferredSize(new java.awt.Dimension(6, 25));

      jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel20.setText("Address:");

      jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
      jTextField11.setPreferredSize(new java.awt.Dimension(6, 25));

      jTextField13.setPreferredSize(new java.awt.Dimension(6, 25));

      jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel21.setText("Registration date:");

      jTextField14.setPreferredSize(new java.awt.Dimension(6, 25));

      jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel22.setText("Payment year:");

      jTextField15.setPreferredSize(new java.awt.Dimension(6, 25));

      jLabel23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel23.setText("Newsletter subscription:");

      jCheckBox2.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jCheckBox2ActionPerformed(evt);
         }
      });

      jScrollPane2.setViewportView(jScrollPane1);

      table = new JTable();
      table.setShowVerticalLines(false);
      table.setFont(new java.awt.Font("Tahoma", 0, 14));

      Object o[][] = new Object[VIASystem.events.getAllEvents().size()][2];

      for (int i = 0; i < VIASystem.events.getAllEvents().size(); i++)
      {
         o[i][1] = VIASystem.events.getAllEvents().get(i);
         o[i][0] = false;
      }

      table.setModel(
            new javax.swing.table.DefaultTableModel(o, new String[] { "", "" })
            {
               Class[] types = new Class[] { java.lang.Boolean.class,
                     java.lang.Object.class };

               public Class getColumnClass(int columnIndex)
               {
                  return types[columnIndex];
               }
            });
      table.setDefaultRenderer(Object.class, new EventTableCellRenderer());
      table.getColumnModel().getColumn(0).setPreferredWidth(28);
      table.getColumnModel().getColumn(0).setMinWidth(28);
      table.getColumnModel().getColumn(1).setPreferredWidth(222);
      jScrollPane1.setColumnHeaderView(table);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
            getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addGap(50, 50, 50)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout
                              .createSequentialGroup().addComponent(jLabel23)
                              .addGap(18, 18, 18).addComponent(jCheckBox2))
                        .addComponent(jLabel19)
                        .addGroup(layout
                              .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                    false)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16).addGap(18, 18, 18)
                                    .addComponent(jScrollPane2,
                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                          475,
                                          javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING,
                                    layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21)
                                                .addComponent(jLabel22)
                                                .addComponent(jLabel20))
                                          .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField13,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                      479,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout
                                                      .createParallelGroup(
                                                            javax.swing.GroupLayout.Alignment.LEADING,
                                                            false)
                                                      .addComponent(
                                                            jTextField14,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            479,
                                                            Short.MAX_VALUE)
                                                      .addComponent(
                                                            jTextField15,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE)))))
                        .addComponent(jSeparator3,
                              javax.swing.GroupLayout.PREFERRED_SIZE, 703,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup().addGap(3, 3, 3)
                              .addGroup(layout.createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                          .addComponent(jButton3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                93,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(18, 18, 18)
                                          .addComponent(jButton4,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                93,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING,
                                          false)
                                          .addComponent(jLabel1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                320,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jSeparator4,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                715,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                      .addGroup(layout
                                                            .createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(
                                                                  jTextField12,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  479,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout
                                                                  .createSequentialGroup()
                                                                  .addGroup(
                                                                        layout.createParallelGroup(
                                                                              javax.swing.GroupLayout.Alignment.LEADING)
                                                                              .addComponent(
                                                                                    jLabel4)
                                                                              .addComponent(
                                                                                    jLabel15))
                                                                  .addGap(85,
                                                                        85, 85)
                                                                  .addGroup(
                                                                        layout.createParallelGroup(
                                                                              javax.swing.GroupLayout.Alignment.LEADING)
                                                                              .addComponent(
                                                                                    jTextField10,
                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                    Short.MAX_VALUE)
                                                                              .addComponent(
                                                                                    jTextField11,
                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                    Short.MAX_VALUE))))
                                                      .addGap(104, 104,
                                                            104))))))
                  .addContainerGap(92, Short.MAX_VALUE)));
      layout.setVerticalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addGap(60, 60, 60)
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                        30, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(20, 20, 20)
                  .addComponent(jSeparator4,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(42, 42, 42)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4).addComponent(jTextField11,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(25, 25, 25)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15).addComponent(jTextField10,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(25, 25, 25)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19).addComponent(jTextField12,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(25, 25, 25)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20).addComponent(jTextField13,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(25, 25, 25)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21).addComponent(jTextField14,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(25, 25, 25)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22).addComponent(jTextField15,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(25, 25, 25)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23).addComponent(jCheckBox2))
                  .addGap(42, 42, 42)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16,
                              javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2,
                              javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                              javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jSeparator3,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 19,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout
                        .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3,
                              javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4,
                              javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                              javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(35, 35, 35)));

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)
         throws IOException
   {// GEN-FIRST:event_jButton3ActionPerformed
      // TODO add your handling code here:

      String name = jTextField11.getText();
      String email = jTextField10.getText();
      String phone = jTextField12.getText();
      String address = jTextField13.getText();
      String regDate = jTextField14.getText();
      String payYear = jTextField15.getText();

      // registration date conversion
      String[] numbers = regDate.split("\\.");

      int[] results = new int[numbers.length];
      try
      {
         for (int i = 0; i < numbers.length; i++)
         {
            results[i] = Integer.parseInt(numbers[i]);
         }
      }
      catch (NumberFormatException e)
      {
         JOptionPane.showMessageDialog(null,
               "Please enter a valid input (use only numbers and dots) \nE.g: 15.12.2017");
      }
      Date regDateObj = new Date(results[0], results[1], results[2]);

      // payment year conversion
      int paymentYear = Integer.parseInt(payYear);

      // getting subscription status
      boolean sub = jCheckBox2.isSelected();

      // getting attended events
      boolean[] values = new boolean[table.getRowCount()];
      TableModel tm = table.getModel();
      ArrayList<String> attendedEvs = new ArrayList<String>();
      for (int i = 0; i < tm.getRowCount(); i++)
      {
         Object o = tm.getValueAt(i, 0);
         values[i] = (boolean) o;
         if (values[i] == true)
         {
            Object obj = table.getValueAt(i, 1);
            Event event = (Event) obj;
            for (int j = 0; j < VIASystem.events.getAllEvents().size(); j++)
            {
               if (VIASystem.events.getAllEvents().get(j).getTitle()
                     .equals(event.getTitle())
                     && VIASystem.events.getAllEvents().get(j).getId() == event
                           .getId())
               {
                  attendedEvs.add(String.valueOf(
                        VIASystem.events.getAllEvents().get(j).getId()));
               }
            }
         }
      }

      Member member = new Member();
      member.setAddress(address);
      member.setDateOfRegistration(regDateObj);
      member.setEmail(email);
      member.setPhone(phone);
      member.setPaymentYear(paymentYear);
      member.setPhone(phone);
      member.setName(name);
      member.setNewsletterSubscription(sub);
      member.setAttendedEvents(attendedEvs);

      member.writeToFile();
      VIASystem.members.addMember(member);

      this.setVisible(false);
      new List_Members().setVisible(true);
   }// GEN-LAST:event_jButton3ActionPerformed

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)
         throws IOException
   {// GEN-FIRST:event_jButton4ActionPerformed
      this.setVisible(false);
      new List_Members().setVisible(true);
   }// GEN-LAST:event_jButton4ActionPerformed

   private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt)
   {// GEN-FIRST:event_jCheckBox2ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jCheckBox2ActionPerformed

   /**
    * @param args
    *           the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
      // (optional) ">
      /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the
       * default look and feel. For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
       * html
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
               .getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(Member_add.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(Member_add.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(Member_add.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(Member_add.class.getName())
               .log(java.util.logging.Level.SEVERE, null, ex);
      }
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>
      // </editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new Member_add().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JCheckBox jCheckBox2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel22;
   private javax.swing.JLabel jLabel23;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JSeparator jSeparator4;
   private javax.swing.JTextField jTextField10;
   private javax.swing.JTextField jTextField11;
   private javax.swing.JTextField jTextField12;
   private javax.swing.JTextField jTextField13;
   private javax.swing.JTextField jTextField14;
   private javax.swing.JTextField jTextField15;
   private JTable table;
}
